### ISSUE TITLE
[FR]: Request module for vManage-client (endpoint and payload as arguments)

### ISSUE THREAD

**Issue by cicharka** [cisco-open/ansible-collection-catalystwan#5]
### Please describe the problem

Example module should look like:
```yml
 - name: Send raw request to vManage
    cisco.vmngclient.request:
        endpoint: "desired endponit"
        payload: "Any dict provided by user, or json, or whatever"
        ...
```

### Please describe the solution you'd like

That requires rethink of handling get/put/post/delete operations, and also payload fetching
